# fly.toml app configuration file generated for cell-tower-map on 2026-05-17T06:24:41Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cell-tower-map'
primary_region = 'dfw'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = 'bundle exec rails db:migrate'

[env]
  MALLOC_ARENA_MAX = '2'
  RAILS_ENV = 'production'
  RAILS_LOG_TO_STDOUT = 'true'
  RAILS_SERVE_STATIC_FILES = 'true'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
