# fly.toml app configuration file generated for towers-react on 2026-05-16T23:54:27-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'towers-react'
primary_region = 'dfw'

[build]
  dockerfile = 'Dockerfile'
  [build.args]
    VITE_GOOGLE_MAPS_API_KEY = ""

[env]
  MALLOC_ARENA_MAX = '2'
  RAILS_ENV = 'production'
  RAILS_LOG_TO_STDOUT = 'true'
  RAILS_SERVE_STATIC_FILES = 'true'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpus = 1
  memory_mb = 256
